# Generated by Django 3.0.7 on 2020-07-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200704_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryAddress',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Delivery Address'),
        ),
    ]
