# Generated by Django 3.0.7 on 2020-07-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200704_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingModule',
        ),
    ]
