# Generated by Django 3.0.7 on 2020-07-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pricingmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryDate',
            field=models.DateField(null=True),
        ),
    ]
