# Generated by Django 3.0.7 on 2020-07-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200706_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelform',
            name='deliveryDate',
            field=models.DateField(),
        ),
    ]
