# Generated by Django 3.0.8 on 2020-07-31 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200706_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfuelform',
            name='gallsRequested',
            field=models.IntegerField(default=1, verbose_name='Gallons Requested'),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='suggPrice',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.00000'), max_digits=100, verbose_name='Suggested Price'),
        ),
        migrations.AlterField(
            model_name='userfuelform',
            name='total',
            field=models.DecimalField(decimal_places=7, default=Decimal('0.00000'), max_digits=100, verbose_name='Total (Price * Gallons)'),
        ),
        migrations.DeleteModel(
            name='PricingModule',
        ),
    ]
